import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { ICharacters } from "interface/characters";
import { getCharacter } from "dh-marvel/services/marvel/marvel.service";
import {
  Typography,
  Container,
  Card,
  CardMedia,
  CardContent,
} from "@mui/material";

interface PropsCharacter {
  character: ICharacters;
}

const CharacterPage: NextPage<PropsCharacter> = ({ character }) => {
  return (
    <>
      <Head>
        <title> Personaje </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodySingle title={character.name}>
        <Typography align="center" gutterBottom variant="h5" component="div">
          Detalle del personaje
        </Typography>
        <Container sx={{ paddingTop: "40px", paddingBottom: "40px" }}>
          <Card sx={{ display: "flex" }}>
            <CardMedia
              sx={{ width: 650, height: "auto" }}
              image={`${character.thumbnail.path}.${character.thumbnail.extension}`}
            />
            <CardContent sx={{ maxWidth: 770, minWidth: 770, padding: "25px" }}>
              <Typography gutterBottom variant="h2" component="div">
                {character.name}
              </Typography>
              <Typography gutterBottom variant="h5" component="div">
                Descripción
              </Typography>
              {character.description === null ||
              character.description === "" ? (
                "Sin descripcion disponible"
              ) : (
                <Typography gutterBottom variant="body1" component="div">
                  {character.description}
                </Typography>
              )}
            </CardContent>
          </Card>
        </Container>
      </BodySingle>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const id = Number(context.params?.id);
  const character = await getCharacter(id);

  return {
    props: {
      character,
    },
  };
};

export default CharacterPage;
