import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { getComics } from "dh-marvel/services/marvel/marvel.service";
import GridComponent from "dh-marvel/components/grid/GridComponent";
import { Result } from "interface";
import { PropsCard } from "../components/comics/ComicCard";

interface Props {
  apiComics: PropsCard[];
}

const Index: NextPage<Props> = ({ apiComics }) => {
  return (
    <>
      <Head>
        <title>Marvel comics</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Comics"}>
        {/* <GridComponent comics={apiComics} /> */}
      </BodySingle>
    </>
  );
};

/* export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const apiComics = await getComics(0, 12);

  res.setHeader("Cache-Control", "public, s-maxage=10, stale-while-revalidate");

  const transformComics: PropsCard[] = apiComics.data.results.map(
    (item: Result) => ({
      id: item.id,
      title: item.title,
      image: `${item.thumbnail.path}.${item.thumbnail.extension}`,
    })
  );

  return {
    props: {
      apiComics: transformComics,
    },
  };
}; */

export default Index;
